name = Pink Cat
author = wayvpet
license = MIT
theme_format = 1
theme_version = 1
aspect_ratio = 500:277

# Configuración geométrica propia del gato rosa
cat_height = 110
cat_align = center
cat_x_offset = 0
cat_y_offset = 0
can_roam = 0
